services:
  insprira:
    image: ghcr.io/coracoo/insprira:latest
    container_name: insprira
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./data:/data
